name: saybye
version: "1.0.0"
summary: Command-line tool for saying byebye to someone
description: |
  saybye
  saybye name
grade: stable
confinement: strict

apps:
  saybye:
    command: saybye

parts:
  saybye:
    plugin: nodejs
    source: .